### ISSUE TITLE
I have a problem with authorization in new account vk

### ISSUE THREAD

**Issue by Merbuz** [imartemy1524/vk_captcha#3]
Hi! I created an account using a number (paid, but not a personal virtual one). At first, I calmly managed to log in to my account, the captcha was solved and everything was OK, but then this error started to come out.

Traceback (most recent call last):
  File "d:\Python\.zakaz\main.py", line 12, in <module>
    bot = StudBot(login=bot_parameters[0], password=bot_parameters[1], app_id=bot_parameters[2])
  File "d:\Python\.zakaz\studnime_api.py", line 23, in __init__
    self.studnime.auth() # Автоматическая авторизация
  File "C:\Users\Iostr\AppData\Local\Programs\Python\Python310\lib\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\Iostr\AppData\Local\Programs\Python\Python310\lib\site-packages\vk_api\vk_api.py", line 207, in _auth_cookies
    self._vk_login()
  File "C:\Users\Iostr\AppData\Local\Programs\Python\Python310\lib\site-packages\vk_api\vk_api.py", line 312, in _vk_login
    return self.error_handlers[CAPTCHA_ERROR_CODE](captcha)
  File "C:\Users\Iostr\AppData\Local\Programs\Python\Python310\lib\site-packages\vk_captcha\solver.py", line 216, in vk_api_captcha_handler
    key, _ = self.solve(captcha.get_url(), minimum_accuracy=minimum_accuracy, repeat_count=repeat_count)
  File "C:\Users\Iostr\AppData\Local\Programs\Python\Python310\lib\site-packages\vk_captcha\solver.py", line 65, in solve
    with logging_lock:
AttributeError: __enter__

**Comment by Merbuz** [comment]
By the way, the account is not blocked / its limitations are not indicated anywhere. I calmly entered it without a script, but now this error always comes out through the script. Maybe I should use old accounts, but I don't have any
